"""Lays out an already-assembled report (report_content.ReportSection list +
pre-rendered map/chart PNGs) into PDF bytes with fpdf2. This module owns ONLY
layout/pagination - it never composes prose (report_content.py does that) and
never talks to GEE/DB/network (report_service.py orchestrates fetching
everything this needs before calling here). That split is what makes
report_content.py's text independently unit-testable without a PDF library at
all, and this module testable with plain fake ReportSection objects."""
from __future__ import annotations

from datetime import datetime
from io import BytesIO

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from app.services.report_content import ReportSection

_MARGIN_MM = 15


def _format_area(ha: float) -> str:
    return f"{ha:,.2f} ha"


def _new_pdf() -> FPDF:
    pdf = FPDF(format="A4")
    pdf.set_margin(_MARGIN_MM)
    pdf.set_auto_page_break(auto=True, margin=_MARGIN_MM)
    return pdf


def _line(pdf: FPDF, h: float, text: str) -> None:
    """multi_cell wrapper that always resets the cursor to the left margin
    for the NEXT line - fpdf2's own multi_cell default leaves X at the end of
    the text it just wrote (useful for inline-continuation layouts, not for
    this report's one-paragraph-per-call style), which otherwise starves the
    following call of horizontal space."""
    pdf.multi_cell(0, h, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def _cover_page(
    pdf: FPDF, project_name: str, project_id: str, generated_at: datetime,
    sections: list[ReportSection],
) -> None:
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 22)
    _line(pdf, 12, "dMRV Analysis Report")
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 15)
    _line(pdf, 9, project_name)
    pdf.set_font("Helvetica", "", 10)
    _line(pdf, 6, f"Project ID: {project_id}")
    _line(pdf, 6, f"Generated: {generated_at.strftime('%Y-%m-%d %H:%M UTC')}")
    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 12)
    _line(pdf, 8, f"Included analyses ({len(sections)}):")
    pdf.set_font("Helvetica", "", 10)
    for s in sections:
        year_note = f" ({s.stats_grid_year})" if s.stats_grid_year else (
            f" ({s.class_breakdown_year})" if s.class_breakdown_year else ""
        )
        _line(pdf, 6, f"  - {s.name}{year_note} - computed {s.computed_at.strftime('%Y-%m-%d')}")
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    _line(
        pdf, 5,
        "This report was generated by the dMRV Analytical Platform. It is self-contained: "
        "every section below reproduces the same summary, statistics, and methodology text "
        "shown in the live application at the time each analysis was computed.",
    )


def _section_page(
    pdf: FPDF, section: ReportSection, map_png: bytes | None, chart_png: bytes | None
) -> None:
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    _line(pdf, 10, section.name)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(90, 90, 90)
    computed = section.computed_at.strftime("%Y-%m-%d %H:%M UTC")
    _line(pdf, 5, f"{section.category} - computed {computed}")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    if section.coverage_pct is not None:
        pdf.set_font("Helvetica", "B", 10)
        _line(pdf, 6, f"Coverage: {section.coverage_pct:.1f}% of the project boundary")

    pdf.set_font("Helvetica", "", 10)
    _line(pdf, 6, section.description)
    pdf.ln(2)

    if map_png:
        pdf.image(BytesIO(map_png), w=pdf.epw, x=pdf.l_margin)
        pdf.set_xy(pdf.l_margin, pdf.y)
        pdf.ln(2)

    if section.summary:
        pdf.set_font("Helvetica", "B", 11)
        _line(pdf, 6, "Summary")
        pdf.set_font("Helvetica", "", 10)
        _line(pdf, 6, section.summary)
        pdf.ln(2)

    if section.class_breakdown:
        pdf.set_font("Helvetica", "B", 11)
        label = "Class breakdown" if section.class_breakdown_year is None else (
            f"Class breakdown ({section.class_breakdown_year})"
        )
        _line(pdf, 6, label)
        pdf.set_font("Helvetica", "", 10)
        for row in section.class_breakdown:
            _line(pdf, 5.5, f"  {row.name}: {_format_area(row.area_ha)}")
        pdf.ln(2)

    if chart_png:
        pdf.set_font("Helvetica", "B", 11)
        _line(pdf, 6, "Year-series trend")
        pdf.image(BytesIO(chart_png), w=pdf.epw * 0.85, x=pdf.l_margin)
        pdf.set_xy(pdf.l_margin, pdf.y)
        pdf.ln(2)

    if section.stats_grid:
        pdf.set_font("Helvetica", "B", 11)
        _line(pdf, 6, f"Distribution statistics ({section.stats_grid_year})")
        pdf.set_font("Helvetica", "", 10)
        for row in section.stats_grid:
            value = f"{row.value:.3f}" if row.value is not None else "no data"
            _line(pdf, 5.5, f"  {row.label}: {value}")
        pdf.ln(2)

    if section.note:
        pdf.set_font("Helvetica", "B", 11)
        _line(pdf, 6, "Methodology")
        pdf.set_font("Helvetica", "", 9)
        _line(pdf, 5, section.note)
        pdf.ln(2)

    pdf.set_font("Helvetica", "BI", 9)
    _line(pdf, 5, section.disclaimer)


def build_report_pdf(
    *,
    project_name: str,
    project_id: str,
    generated_at: datetime,
    sections: list[ReportSection],
    map_images: dict[str, bytes],
    chart_images: dict[str, bytes],
) -> bytes:
    """`map_images`/`chart_images` are keyed by `analysis_id`, absent keys
    simply render that section without the image (never a hard failure - a
    single analysis' map-tile fetch failing must not sink the whole report,
    same tolerance principle as report_map_image.py's own per-tile handling)."""
    pdf = _new_pdf()
    _cover_page(pdf, project_name, project_id, generated_at, sections)
    for section in sections:
        _section_page(
            pdf, section,
            map_images.get(section.analysis_id), chart_images.get(section.analysis_id),
        )
    return bytes(pdf.output())
