"""Lays out an already-assembled report (report_content.ReportSection list +
pre-rendered map/chart PNGs) into PDF bytes with fpdf2. This module owns ONLY
layout/pagination - it never composes prose (report_content.py does that) and
never talks to GEE/DB/network (report_service.py orchestrates fetching
everything this needs before calling here). That split is what makes
report_content.py's text independently unit-testable without a PDF library at
all, and this module testable with plain fake ReportSection objects."""
from __future__ import annotations

from datetime import datetime
from io import BytesIO

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from app.domain.enums import ReportType
from app.services.report_content import ReportSection

_MARGIN_MM = 15

# Wave: ai-report-narrative, Phase 3 (carbon-mrv-vm0047 review fixes, R2).
# Fixed template - only `{model}` ever varies, and it is filled in ONLY by
# build_report_pdf's `ai_model` parameter (sourced server-side from
# `ai_narrative.GEMINI_MODEL`, a fixed constant), never from a section's
# narrative text or anything else that passed through the model - nothing in
# the narrative path can spoof which model is named here. The rest of the
# string is a constant so the disclosure itself cannot drift between report
# runs.
#
# Deliberately does NOT say "validated" (that word has a specific Verra/VVB
# meaning and reads as endorsement) and explicitly states everything a VVB
# reader would need to not mistake this for the deterministic report
# index_summary.py's own docstring says a VVB may read: non-reproducibility,
# lack of review, which parts are still deterministic, the banned-claims
# list, and that this is not the document to submit for validation/
# verification.
AI_NARRATIVE_DISCLOSURE_TEMPLATE = (
    "This report's narrative summary text was generated by the AI model \"{model}\" from "
    "the analysis data shown in this report. It is NOT reproducible: running the same "
    "analysis through this model again, today or later, can produce different wording from "
    "the same numbers. It has NOT been reviewed or verified by any person. The statistics, "
    "maps, and charts in this report come from the same deterministic computation pipeline "
    "as the system-generated report and are identical to it - the AI model never sees or "
    "alters them. The narrative text itself is descriptive only: it is not a "
    "forest-definition, eligibility, additionality, baseline, leakage, permanence, "
    "uncertainty, or carbon determination. This report is not intended for submission to a "
    "validation/verification body - use the system-generated report instead for "
    "audit-facing purposes."
)


def _format_area(ha: float) -> str:
    return f"{ha:,.2f} ha"


# fpdf2's core Helvetica font checks every string against `FPDF.
# core_fonts_encoding`, which defaults to plain "latin-1" (ISO-8859-1) - NOT
# Windows-1252/cp1252 as fpdf2's own error message's phrasing might suggest.
# That means the common "smart" typography an LLM reaches for by default -
# en/em dash, curly quotes, bullet, ellipsis - is ALSO out of range, not just
# obscure math symbols; cp1252 would have covered those (they sit in its
# 0x80-0x9F block) but latin-1 leaves that block as unused control codes.
# Real dmrv-qa failure (hansen_gfc, 2026-08-12): a real Gemini narrative wrote
# "canopy cover ≥15%" using the Unicode "≥" glyph rather than plain ASCII
# ">=" - fpdf2 raised on that ONE character partway through rendering, which
# would otherwise dead-letter the entire report over a single symbol in a
# single field. AI-generated text is the highest-risk source (deterministic/
# fixed text here is all authored ASCII, but nothing stops an LLM from
# reaching for real Unicode typography), but this maps onto the single
# chokepoint every string in this module passes through (`_line` below), so
# it protects every text source uniformly, not just the AI path.
_UNICODE_ASCII_FALLBACKS = {
    "≥": ">=", "≤": "<=", "×": "x", "÷": "/",
    "→": "->", "←": "<-", "✓": "OK", "✗": "x",
    "–": "-", "—": "-", "‘": "'", "’": "'",
    "“": '"', "”": '"', "•": "-", "…": "...", "™": "(TM)",
}


def _pdf_safe_text(text: str) -> str:
    """Replaces the specific out-of-latin-1 symbols above with ASCII, then -
    for anything else neither anticipated here nor in latin-1 (an emoji, a
    non-Latin script, a symbol nobody's seen yet) - falls back to "?" via
    `errors="replace"` rather than letting fpdf2 raise and sink the whole
    report over one unanticipated character. "latin-1" here matches fpdf2's
    OWN `core_fonts_encoding` default exactly, not cp1252 or anything looser -
    this must stay in lockstep with whatever fpdf2 actually checks against."""
    for char, replacement in _UNICODE_ASCII_FALLBACKS.items():
        if char in text:
            text = text.replace(char, replacement)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _new_pdf() -> FPDF:
    pdf = FPDF(format="A4")
    pdf.set_margin(_MARGIN_MM)
    pdf.set_auto_page_break(auto=True, margin=_MARGIN_MM)
    return pdf


def _line(pdf: FPDF, h: float, text: str) -> None:
    """multi_cell wrapper that always resets the cursor to the left margin
    for the NEXT line - fpdf2's own multi_cell default leaves X at the end of
    the text it just wrote (useful for inline-continuation layouts, not for
    this report's one-paragraph-per-call style), which otherwise starves the
    following call of horizontal space."""
    pdf.multi_cell(0, h, _pdf_safe_text(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)


# Wave: ai-report-narrative, Phase 3 (carbon-mrv-vm0047 review fixes, R1).
# `report_type=system`'s claim - "every section reproduces the same summary
# shown in the live app" - is simply false for `report_type=ai`: the summary
# is LLM-generated, not what the live app shows, and 8 of the 13 analysis
# types show no summary in the live app at all today. Two separate strings,
# not one paragraph softened, so each report type states only what is
# actually true of it.
_COVER_TEXT_SYSTEM = (
    "This report was generated by the dMRV Analytical Platform. It is self-contained: "
    "every section below reproduces the same summary, statistics, and methodology text "
    "shown in the live application at the time each analysis was computed."
)
_COVER_TEXT_AI = (
    "This report was generated by the dMRV Analytical Platform. Its maps, statistics and "
    "methodology text are identical to the system-generated report and reproduce exactly "
    "what the platform computed for each analysis. The narrative summary text in each "
    "section below is NOT what the live application shows - most analysis types show no "
    "summary in the live application at all - it is written by an AI model from that same "
    "underlying data. See the disclosure below for what that means."
)


def _cover_page(
    pdf: FPDF, project_name: str, project_id: str, generated_at: datetime,
    sections: list[ReportSection], report_type: str, ai_model: str | None = None,
) -> None:
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 22)
    _line(pdf, 12, "dMRV Analysis Report")
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 15)
    _line(pdf, 9, project_name)
    pdf.set_font("Helvetica", "", 10)
    _line(pdf, 6, f"Project ID: {project_id}")
    _line(pdf, 6, f"Generated: {generated_at.strftime('%Y-%m-%d %H:%M UTC')}")
    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 12)
    _line(pdf, 8, f"Included analyses ({len(sections)}):")
    pdf.set_font("Helvetica", "", 10)
    for s in sections:
        year_note = f" ({s.stats_grid_year})" if s.stats_grid_year else (
            f" ({s.class_breakdown_year})" if s.class_breakdown_year else ""
        )
        _line(pdf, 6, f"  - {s.name}{year_note} - computed {s.computed_at.strftime('%Y-%m-%d')}")
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    if report_type == ReportType.AI:
        _line(pdf, 5, _COVER_TEXT_AI)
        pdf.ln(3)
        assert ai_model, "ai_model is required when report_type=ai"  # noqa: S101
        _line(pdf, 5, AI_NARRATIVE_DISCLOSURE_TEMPLATE.format(model=ai_model))
    else:
        _line(pdf, 5, _COVER_TEXT_SYSTEM)


def _heading(pdf: FPDF, text: str) -> None:
    pdf.set_font("Helvetica", "B", 11)
    _line(pdf, 6, text)
    pdf.set_font("Helvetica", "", 10)


def _body(pdf: FPDF, text: str) -> None:
    _line(pdf, 6, text)
    pdf.ln(2)


def _bulleted(pdf: FPDF, text: str) -> None:
    for bullet in text.split("\n"):
        if bullet.strip():
            _line(pdf, 5.5, f"- {bullet.strip()}")
    pdf.ln(2)


def _section_page(
    pdf: FPDF, section: ReportSection, map_png: bytes | None, chart_png: bytes | None
) -> None:
    """Wave: 11-section report restructure. Fixed 1-11 order for every
    analysis type. Sections 2/3/4/9/10/11 are always populated (never gate on
    truthiness); sections 6/7 (Temporal/Change Analysis) omit their heading
    entirely when the capability check that gates them
    (`report_content.has_temporal_data`/`has_change_data`) found nothing -
    `section.narrative` simply has no key for them in that case, same
    truthy-check idiom every optional block here has always used."""
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    _line(pdf, 10, section.name)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(90, 90, 90)
    computed = section.computed_at.strftime("%Y-%m-%d %H:%M UTC")
    _line(pdf, 5, f"{section.category} - computed {computed}")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    if section.coverage_pct is not None:
        pdf.set_font("Helvetica", "B", 10)
        _line(pdf, 6, f"Coverage: {section.coverage_pct:.1f}% of the project boundary")

    if map_png:
        pdf.set_font("Helvetica", "", 10)
        pdf.image(BytesIO(map_png), w=pdf.epw, x=pdf.l_margin)
        pdf.set_xy(pdf.l_margin, pdf.y)
        pdf.ln(2)

    if section.narrative.get("executive_summary"):
        _heading(pdf, "1. Executive Summary")
        _body(pdf, section.narrative["executive_summary"])

    _heading(pdf, "2. Methodology")
    _body(pdf, section.methodology_text)

    _heading(pdf, "3. Data & Processing")
    _body(pdf, section.data_processing_text)

    if section.class_breakdown or section.stats_grid:
        _heading(pdf, "4. Statistics")
        pdf.set_font("Helvetica", "", 10)
        if section.class_breakdown:
            label = "Class breakdown" if section.class_breakdown_year is None else (
                f"Class breakdown ({section.class_breakdown_year})"
            )
            _line(pdf, 5.5, label)
            for class_row in section.class_breakdown:
                _line(pdf, 5.5, f"  {class_row.name}: {_format_area(class_row.area_ha)}")
        if section.stats_grid:
            # `stats_grid_year` is None for a VNV band-index result (one
            # rolling 90-day window, no year axis - see report_content.py's
            # own `"index" in stats` branch) - same None-safe pattern
            # `class_breakdown`'s own label above already uses, so this never
            # literally prints "Distribution statistics (None)".
            stats_label = "Distribution statistics" if section.stats_grid_year is None else (
                f"Distribution statistics ({section.stats_grid_year})"
            )
            _line(pdf, 5.5, stats_label)
            for stat_row in section.stats_grid:
                value = f"{stat_row.value:.3f}" if stat_row.value is not None else "no data"
                _line(pdf, 5.5, f"  {stat_row.label}: {value}")
        pdf.ln(2)

    if chart_png:
        pdf.set_font("Helvetica", "B", 11)
        _line(pdf, 6, "Year-series trend")
        pdf.image(BytesIO(chart_png), w=pdf.epw * 0.85, x=pdf.l_margin)
        pdf.set_xy(pdf.l_margin, pdf.y)
        pdf.ln(2)

    if section.narrative.get("spatial_distribution"):
        _heading(pdf, "5. Spatial Distribution")
        _body(pdf, section.narrative["spatial_distribution"])

    if section.narrative.get("temporal_analysis"):
        _heading(pdf, "6. Temporal Analysis")
        _body(pdf, section.narrative["temporal_analysis"])

    if section.narrative.get("change_analysis"):
        _heading(pdf, "7. Change Analysis")
        _body(pdf, section.narrative["change_analysis"])

    if section.narrative.get("key_findings"):
        _heading(pdf, "8. Key Findings")
        _bulleted(pdf, section.narrative["key_findings"])

    _heading(pdf, "9. Carbon Project Relevance")
    _body(pdf, section.carbon_project_relevance)

    _heading(pdf, "10. Data Quality")
    _body(pdf, section.data_quality_text)

    _heading(pdf, "11. Limitations")
    pdf.set_font("Helvetica", "", 9)
    _body(pdf, section.limitations_text)

    pdf.set_font("Helvetica", "BI", 9)
    _line(pdf, 5, section.disclaimer)


def build_report_pdf(
    *,
    project_name: str,
    project_id: str,
    generated_at: datetime,
    sections: list[ReportSection],
    map_images: dict[str, bytes],
    chart_images: dict[str, bytes],
    report_type: str = ReportType.SYSTEM,
    ai_model: str | None = None,
) -> bytes:
    """`map_images`/`chart_images` are keyed by `analysis_id`, absent keys
    simply render that section without the image (never a hard failure - a
    single analysis' map-tile fetch failing must not sink the whole report,
    same tolerance principle as report_map_image.py's own per-tile handling).

    `report_type="ai"` swaps in `_COVER_TEXT_AI` (R1) and appends
    `AI_NARRATIVE_DISCLOSURE_TEMPLATE` filled in with `ai_model` (R2) on the
    cover page - every section's own layout is unchanged; the caller
    (report_service.generate_report_pdf_bytes) is responsible for having
    already sourced each section's `narrative` dict from the AI narrative
    before it ever reaches this function, which itself has no idea where a
    section's text came from. `ai_model` MUST be the caller's own
    `ai_narrative.GEMINI_MODEL` (a fixed constant) - never anything derived
    from a section's narrative or any other model-generated content, or the
    disclosure could be spoofed to name a different model than the one that
    actually ran. Required (not optional) whenever `report_type="ai"` - see
    the assertion in `_cover_page`."""
    pdf = _new_pdf()
    _cover_page(pdf, project_name, project_id, generated_at, sections, report_type, ai_model)
    for section in sections:
        _section_page(
            pdf, section,
            map_images.get(section.analysis_id), chart_images.get(section.analysis_id),
        )
    return bytes(pdf.output())
